name: Enforces Pull Request Title to include Jira Issue Key
description: Checks if a PR title starts with a Jira Issue Key
inputs:
  projectKey:
    description: 'A specific Jira Project Key that must be included.'
    required: false
runs:
  using: node12
  main: dist/index.js
